# This is a basic workflow to help you get started with Actions

name: Update ArmoniK.Api

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "Test"
          git config --global user.email "test@test.fr"
  
      - name: Clone ArmoniK.Api
        run: |
          git clone https://${{ secrets.TOKEN }}@github.com/aneojgurhem/ArmoniK.Api.git --recursive

      - name: Update ArmoniK.Api
        run: |
          cd ArmoniK.Api
          git submodule update --remote

      - name: Modify ArmoniK.Api
        run: |
          cd ArmoniK.Api
          git commit -a -m "Test"
          git show

      - name: Push ArmoniK.Api
        run: |
          cd ArmoniK.Api
          echo $(git rev-parse --abbrev-ref HEAD)
          git push origin $(git rev-parse --abbrev-ref HEAD)
