# This is a basic workflow to help you get started with Actions

name: Update ArmoniK.Api

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

jobs:
  build:
    uses: aneojgurhem/ArmoniK.Proto/.github/workflows/update-workflow.yml@main
    with:
      name: ${{ github.event.head_commit.committer.name }}
      email: ${{ github.event.head_commit.committer.email }}
      repos: ["github.com/aneojgurhem/ArmoniK.Api.git"]
      message: ${{ github.event.head_commit.message }}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

