# This is a basic workflow to help you get started with Actions

name: Update ArmoniK.Api

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths:
      - '**.proto'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.event.head_commit.committer.name }}"
          git config --global user.email "${{ github.event.head_commit.committer.email }}"
  
      - name: Update ArmoniK.Api
        run: |
          git clone https://github.com/aneoconsulting/ArmoniK.Api.git --recursive
          cd ArmoniK.Api
          git submodule foreach git pull
          git commit -a -m "${{ github.event.head_commit.message }}"
          #git push origin $(git rev-parse --abbrev-ref HEAD)
